name: mqtt5_client
description: A server and browser based MQTT5 client for Dart supporting normal, secure sockets and websockets.
version: 2.0.0
homepage: https://github.com/shamblett/mqtt5_client

environment:
 sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
 typed_data: '^1.1.6'
 event_bus: '^1.1.1'
 path: '^1.6.4'
 crypto: '^2.1.5'
 meta: '^1.1.8'
 observable: '^0.22.2'

dev_dependencies:
 test: '^1.15.1'
 mockito: '^5.0.0-nullsafety.5'
 pedantic: '^1.9.0'
 pana: '^0.14.10'
 build_runner: '^1.11.0'
 build_test: '^1.3.4'
 build_web_compilers: '^2.16.0'





