name: mqtt5_client
description: A server and browser based MQTT5 client for Dart supporting normal, secure sockets and websockets.
version: 2.1.0
homepage: https://github.com/shamblett/mqtt5_client

environment:
 sdk: ">=2.6.0 <3.0.0"

dependencies:
 typed_data: '^1.1.6'
 event_bus: '^1.1.1'
 path: '^1.6.4'
 crypto: '^2.1.4'
 meta: '^1.1.8'
 observable: '^0.22.2'

dev_dependencies:
 test: '^1.15.1'
 mockito: '^4.1.1'
 pedantic: '^1.9.0'
 pana: '^0.13.13'
 build_runner: '^1.10.0'
 build_test: '^1.2.0'
 build_web_compilers: '^2.11.0'





